spring:
  data:
    mongodb:
      authentication-database: admin
      host: ${MONGO_HOST:some-mongo}
      port: 27017
      database: "test"
      username: "mongoadmin"
      password: "secret"

server:
  port: 80