spring:
  data:
    mongodb:
      authentication-database: ${MONGO_AUTH_DB}
      host: ${MONGO_HOST}
      port: ${MONGO_HOST_PORT}
      database: ${MONGO_DATABASE_NAME}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}

server:
  port: 80